# Number of worker nodes to provision
NUM_OF_WORKERS = 3

Vagrant.configure("2") do |config|

  # Set default VM configuration
  config.ssh.password = "vagrant"
  config.ssh.username = "vagrant"
  config.vm.box = "../../packer/boxes/ubuntu-server-22.04.box"
  config.vm.box_check_update = true
  config.vm.synced_folder "./files/", "/vagrant"

  # Main cluster node
  config.vm.define "main" do |main|
    # Set VM name
    main.vm.hostname = "k8s-main"

    # Set network address
    main.vm.network "public_network", bridge: "enp12s0", ip: "10.0.3.40"

    # Configure VM
    main.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.default_nic_type = "virtio"
      v.gui = false
      v.linked_clone = true
      v.memory = 4096
      v.name = "k8s-main"
    end

    # Configure DNS server
    main.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "files/bind/main.yml"
    end

    # Configure NFS server
    main.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "files/nfs/main.yml"
    end

    # Configure common cluster components
    main.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "files/k8s/common.yml"
    end

    # Configure main cluster node
    main.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "files/k8s/main.yml"
    end

    # Remove the cluster join script after destroy
    main.trigger.after :destroy do |trigger|
      trigger.info = "Removing cluster temp files..."
      trigger.run = {inline: "bash -c 'rm -rf ./files/k8s/temp/*'"}
    end
  end

  # Worker nodes
  (1..NUM_OF_WORKERS).each do |i|
    config.vm.define "worker0#{i}" do |worker|

      # Set VM name
      worker.vm.hostname = "k8s-worker0#{i}"

      # Set network address
      worker.vm.network "public_network", bridge: "enp12s0", ip: "10.0.3.4#{i}"

      # Configure VM
      worker.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.gui = false
        v.linked_clone = true
        v.memory = 8192
        v.name = "k8s-worker0#{i}"
      end

      # Configure common cluster components
      worker.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "files/k8s/common.yml"
      end

      # Join the cluster
      worker.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "files/k8s/worker.yml"
      end

      # If this is the last worker node, deploy required cluster components
      if i == NUM_OF_WORKERS
        # Setup Nginx ingress controller and MetalLB load balancer
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/load-balancer/main.yml"
        end

        # Setup Kubernetes dashboard
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/dashboard/main.yml"
        end

        # Setup NFS provisioner
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/nfs-provisioner/main.yml"
        end

        # Setup Hashicorp Vault
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/vault/main.yml"
        end

        # Setup cert-manager
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/cert-manager/main.yml"
        end
      end
      
      # If this is the last worker node, deploy optional services
      if i == NUM_OF_WORKERS
        # Setup AWX
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/awx/main.yml"
        end

        # Setup Consul
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/consul/main.yml"
        end

        # Setup Grafana
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/grafana/main.yml"
        end

        # Setup Jenkins
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/jenkins/main.yml"
        end

        # Setup Ping stack
        worker.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "files/inventory"
          ansible.limit = 'all'
          ansible.playbook = "files/k8s/services/ping/main.yml"
        end
      end
    end
  end
end
